spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: dwalin
      password: 1TRF8TnEEN

server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false